### ISSUE TITLE
[Question]: How to get items with PermissionStatus.permanentlyDenied status to show up in iOS Settings

### ISSUE THREAD

**Issue by stephenjen** [Baseflow/flutter-permission-handler#1202]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [ ] Android
- [X] iOS
- [ ] Windows

### Your question

During testing I denied permission for access to the calendar multiple times, and as it is designed to do, after two times iOS started to give status of PermissionStatus.permanentlyDenied.

I used to be able to go into Settings > myApp to toggle the permission to enable access to calendar so I can continue to test other features of my app.  I haven’t tested the permissions portion of my app for some time and today I noticed that I’m getting the PermissionStatus.permanentlyDenied status.  What’s strange is I don’t see the toggle for calendar access in Settings > myApp.  Actually, I didn’t see my app in Settings until I manually added a Root.plist through Xcode.

This is happening both in the simulation app and TestFlight app.

What can I do to fix this issue?  I need to be able to either reset the permissions, which I read is not possible, or somehow have permission_handler trigger toggle to appear in Settings.

Here are the relevant sections of my info.plist and Podfile:

Info.plist:
`<key>NSCalendarsUsageDescription</key>
	<string>Access most functions for calendar for viewing and editing.</string>`

Podfile:
```
        # Start of the permission_handler configuration
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
          # You can enable the permissions needed here. For example to enable camera
          # permission, just remove the `#` character in front so it looks like this:
          #
          # ## dart: PermissionGroup.camera
          # 'PERMISSION_CAMERA=1'
          #
          #  Preprocessor definitions can be found in: https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler_apple/ios/Classes/PermissionHandlerEnums.h
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
            '$(inherited)',

            ## dart: PermissionGroup.calendar
            'PERMISSION_EVENTS=1',

            ## dart: PermissionGroup.photos
            'PERMISSION_PHOTOS=1',

            ## dart: PermissionGroup.notification
            'PERMISSION_NOTIFICATIONS=1',
          ]
        end
        # End of the permission_handler configuration
```

### Version

11.0.0

**Comment by stephenjen** [comment]
I changed the bundle identifier and the problem still occurs.  Strange, as it is a whole new app.

**Comment by mvanbeusekom** [comment]
Hi @stephenjen,

I am unable to reproduce this problem in the [example](https://github.com/Baseflow/flutter-permission-handler/tree/main/permission_handler/example) app. 

When the app starts I can request calendar permission and when I deny access the "Calendars" option shows up in the iOS settings ("Settings" -> "Example" (name of the app) -> "Calendars").

I am no expert on the `Podfile` unfortunately, but something that catches my eye in the configuration you posted is the following line:

```
config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
```

This line is not part of the [podfile](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/example/ios/Podfile) in our example app, I am just wondering if this might cause problems when you are running the app on a device with a different iOS version.

Alternatively, try deleting the app from the test device, wait a minute (so iOS can process settings) and try again.

Hope this helps. If not could you provide an example application that reproduces the issue so we can have a look as well?

**Comment by mvanbeusekom** [comment]
Hi @stephenjen,

A quick update from my side. I am now able to reproduce the issue. I have created a brand new Flutter application, added the configuration you mentioned which results in the behaviour you described.

Initial debugging shows that the pre-processing definitions configured in the `Podfile` are taken into account. In other words when I debug the application the default configuration (which is "all permissions are disabled") is applied which indeed results in directly showing/ returning a `permanentlyDenied` status.

I will continue debugging this issue and hopefully can comeback with a solution shortly.

**Comment by mvanbeusekom** [comment]
Hi @stephenjen,

Doing some more research this problem seems to be related to changes for calendar permissions on iOS 17. I have tested on both iOS 16.4 and iOS 17. Where on iOS 16.4 everything is working fine, on iOS 17 the behaviour you describe occurs.

There is already a PR (#1151) in flight to support the new permission features on iOS 17 and should land soon.

**Comment by stephenjen** [comment]
Hi @mvanbeusekom, thank you for looking into this and for the updates.  Let's hold off and see if support for iOS 17 resolves this issue.

**Comment by JeroenWeener** [comment]
Hi @stephenjen, we just released version `11.1.0` of the permission handler, which might solve your problem, as @mvanbeusekom pointed out.

Could you verify whether the release fixed your problem?
Happy to hear from you!

**Comment by stephenjen** [comment]
@JeroenWeener, unfortunately, I'm still having the same issue.  Updated it to 11.1.0 (and also updated Flutter to 3.16.0), deleted the app off the simulator, build and then installed on the simulator.  

When `PermissionStatus status = await Permission.calendarFullAccess.request();` is executed I still get PermissionStatus.denied and and still not seeing the settings for this app in iOS Settings.  Only when permission is triggered and granted for photos do I see the settings for the app in iOS Settings > myApp, but no toggle for calendar permission.

I also change the bundle ID for the app, but still no good.

**Comment by stephenjen** [comment]
Issue resolved in another thread: https://github.com/Baseflow/flutter-permission-handler/issues/1108#issuecomment-1826979829

**Comment by mev007** [comment]
> Проблема решена в другой теме: [#1108 (комментарий)](https://github.com/Baseflow/flutter-permission-handler/issues/1108#issuecomment-1826979829)

And this solution does not help. You have to restart the program completely
