### ISSUE TITLE
my location is grand when in use ,but Permission.locationAlways.status.isGranted return  true

### ISSUE THREAD

**Issue by philos3** [Baseflow/flutter-permission-handler#323]
## 🐛 Bug Report

AS you see ,this pictrue show us that ,my location is grand when in use ,but Permission.locationAlways.status.isGranted return  true,how can I get the status with always?

![image](https://user-images.githubusercontent.com/8424317/84134743-9f633600-aa7b-11ea-9174-d2c3980cc348.png)

### Expected behavior
Permission.locationAlways.status.isGranted return  false,unless I selected my app location setting at always

### Reproduction steps
when request location permission,selecte when in use,check Permission.locationAlways.status.isGranted

### Configuration
  permission_handler: ^5.0.0+hotfix.9

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
[✓] Connected device (1 available)

• No issues found!
philos:ios zby0520$ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/zby0520/flutter/flutter
    • Framework revision 0b8abb4724 (4 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/zby0520/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-R, build-tools 29.0.2
    • Java binary at: /Users/zby0520/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/zby0520/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
    • IntelliJ at /Users/zby0520/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[✓] Connected device (1 available)
    • iPhone • • ios • iOS 13.3

**Comment by mvanbeusekom** [comment]
@philos3 thank you for reaching out, unfortunately we made a mistake in 5.0.0+hotfix.9 which is now corrected in version 5.0.0+hotfix.10 (and version 5.0.1).

**Comment by philos3** [comment]
> @philos3 thank you for reaching out, unfortunately we made a mistake in 5.0.0+hotfix.9 which is now corrected in version 5.0.0+hotfix.10 (and version 5.0.1).

this problem is still the same when i use  version 5.0.1 ，please have a look at this problem , thanks for your help~
#300

**Comment by philos3** [comment]
> @philos3 thank you for reaching out, unfortunately we made a mistake in 5.0.0+hotfix.9 which is now corrected in version 5.0.0+hotfix.10 (and version 5.0.1).

#300

**Comment by philos3** [comment]
1) If I asked for always permission and   chooses Allow While in Use your app will think it got the .authorizedAlways permission but this is the provisional .authorizedAlways permission.（so flutter-permission-handler return true when the first runtime of my app）

2) Next, when my app would normally receive location events in the background iOS does not directly launches your app in the background with the events but waits until it thinks the user is not doing anything and it then will present this dialog:

### Expected behavior

Permission.locationAlways.status.isGranted return false, when the first runtime of my app,because i chose While in Use  (the permission dialog never povide the choice of always)
