### ISSUE TITLE
Android Camera permission: Permission.camera.status returns undetermined when it should be permanentlyDenied

### ISSUE THREAD

**Issue by viplavrawal** [Baseflow/flutter-permission-handler#336]
## 🐛 Bug Report

Permission.camera.status returns undetermined if called immediately after the user permanentlyDenies the access.
In older android versions, keeps returning undetermined for longer whiles than in android 10 when the user clicks on permanentlyDenied option.

### Reproduction steps
1. Request user for permission
2. Permanently deny the permission from the user's end
3. Ask for permission status 

### Actual behavior
The permission status is returned as undetermined once.
Requesting the permission status again returns it as permanentlyDenied.

### Expected behaviour
The permission status should be returned as permanentlyDenied.

### Configuration
**Version:** ^5.0.0+hotfix.3
```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.5 19F101, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.46.1)
[✓] Connected device (1 available)

• No issues found!
```

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by DhavalRKansara** [comment]
I am also facing the same issues @viplavrawal have you find any solution or workaround for the same?

**Comment by mvanbeusekom** [comment]
@viplavrawal can you reproduce this bug with the latest version (5.0.1+1)? Maybe you can also check out the example App, does the problem occur there as well?

**Comment by mvanbeusekom** [comment]
#338

**Comment by DhavalRKansara** [comment]
> GENERIC_PREFERENCES

@mvanbeusekom yes, I am facing this issue with the latest version (5.0.1+1). And No we are not using `GENERIC_PREFERENCES`  for storing any value in the shared preferences.

Also with version 4.0.0, it is working fine and the library returns me the perfect status of the permission as in case of denied and if I denied with never ask again then it returns me `PermissionStatus.neverAskAgain`. So may b the issues with the latest version only or something else I'm not sure about that.

**Comment by Arkangel12** [comment]
i just add 5.0.1+1 to my app and this is still happening i'm always receiving. `PermissionStatus.undetermined` any updates?

**Comment by DhavalRKansara** [comment]
@mvanbeusekom Is there any update on this?

**Comment by koskimas** [comment]
I also get `undetermined` for `Permission.storage.status` after I've denied access with "deny and never ask me again" button on android. I'm on version 5.0.1+1. I'm the same thing happens for all permissions and not just camera?

**Comment by mikeesouth** [comment]
Any news? Any workaround? This is a real pain.

**Comment by Sempakonka** [comment]
Hi
I was not able to reproduce, but it seems a lot of people have this issue. 
Maybe [this](https://github.com/Baseflow/flutter-permission-handler/issues/390#issuecomment-730198451) solution helps.

**Comment by koskimas** [comment]
@Sempakonka This happens on every device I've tested and on every app I've tested it in. It's extremely weird if you are not able to reproduce this.

**Comment by yaizudamashii** [comment]
@Sempakonka 's suggestion also runs permission request, resulting in the same exception.

I'm also facing this issue, while using add-to-app in Flutter.  One thing I'd like to share is that Flutter [shared_preferences](https://pub.dev/packages/shared_preferences) also doesn't work with add-to-app, maybe there is something with using Android's shared preferences via channel.

**Comment by yaizudamashii** [comment]
Update, I'm encountering this issue with Android API level 30, on fully Flutter app (not add-to-app)

**Comment by moodstubos** [comment]
> Update, I'm encountering this issue with Android API level 30, on fully Flutter app (not add-to-app)

same here. 
I was already on permission_handler 5.x for some time. Today a pub upgrade brakes my storage permission status (always undetermined although it is granted).

logcat says:
`No permissions found in manifest for: 15`
(15 is the enum for storage group)

of cause permission is defined in manifest. 

I tried to downgrade back to an old 5.x version but no success. Now I am using 
`  permission_handler: 4.4.0+hotfix.4`
and it works again (with PermissionHandler().checkPermissionStatus(..) )

**Comment by RomanKapshuk** [comment]
> I was already on permission_handler 5.x for some time. Today a pub upgrade breaks my storage permission status

Same issue here. Please, fix this bug asap

**Comment by claudiowagner** [comment]
Same issue here.
Something is wrong with the "platform_interface" project in version 2.0.2 ...

I put this in my pubspec.yaml and it worked:
```
 permission_handler: 5.0.1+1
 permission_handler_platform_interface: 2.0.1
```

**Comment by mvanbeusekom** [comment]
@moodstubos, @RomanKapshuk, @claudiowagner, a fix is on its way should be uploaded in 30 minutes.

**Comment by mvanbeusekom** [comment]
@moodstubos, @RomanKapshuk, @claudiowagner, I have just released hotfix 5.1.0+2 which should fix this problem. Someone from the community added a new permission to iOS and updated the constants but forgot to do the same on Android. I also completely overlooked it, causing this problem.

**Comment by moodstubos** [comment]
@mvanbeusekom thanks a lot for your explanation. I will try the fix.

**Comment by yaizudamashii** [comment]
@moodstubos Hmm I tried 5.1.0+2 but I'm still seeing the same issue.  Are you using `flutter channel stable`?

**Comment by kikunantoka** [comment]
I also tried `5.1.0+2` but I'm still seeing the same issue.
I use with `shared_preferences` package. I think problems caused by using with `shared_preferences` package is still remaining. It is related #380 .
My work around is use with `request()` . ( ex. `Permission.storage.request().isGranted` ) It seems to return correct value.

**Comment by yaizudamashii** [comment]
@kikunantoka I am also using `shared_preferences`, however with or without the package I am getting incorrect `PermissionStatus` from this package.

By using `.request()` the future does not finish the first time, and the second time it is called, I get an exception
`A request for permissions is already running, please wait for it to finish before doing another request (note that you can request multiple permissions at the same time).`

**Comment by yousifAlneamy** [comment]
This issue should be opened again

**Comment by mvanbeusekom** [comment]
Seems this issue is discussing two different problems. I have solved one but never the original problem.

**Comment by santosh1248** [comment]
i am using API 30 AVD ,not able to open camera...

**Comment by mvanbeusekom** [comment]
Since the release of version 6.0.1 of the permission_handler the original issue should now also be solved.
