### ISSUE TITLE
Microphone permission always returns permanentlyDenied on iOS

### ISSUE THREAD

**Issue by abhinavsingh** [Baseflow/flutter-permission-handler#574]
## 🐛 Bug Report

1. `permanentlyDenied` is being returned on `iOS` devices for `Microphone` permission
2. This happen even when user has just installed the application.  All future requests of-course again result in same response.
3. Our app uses one other permission `Contact` which seems to work fine.

We discovered this today after adding microphone related permissions in our app.  From the docs, `permanentlyDenied` is Android only, so unsure why are we even getting this on iOS devices.

<img width="367" alt="Screen Shot 2021-05-29 at 4 18 00 PM" src="https://user-images.githubusercontent.com/126065/120067477-71ff0600-c099-11eb-81fe-86c946897073.png">

### Expected behavior

Microphone Permission dialog must open

### Reproduction steps

Our code goes through following `askPermission` function.

```
/// Asks for contact permission.
Future<void> askPermissions(Permission requestedPermission,
    CompletionCallback completionCallback) async {
  // Check permission status
  PermissionStatus status = await requestedPermission.status;
  // Request permission
  if (status != PermissionStatus.granted &&
      status != PermissionStatus.permanentlyDenied) {
    status = await requestedPermission.request();
  }
  completionCallback(status);
}
```

Here is how we check for `Microphone` permission before making the call.

```
Future<void> ensurePermissionAndMakeCall(
    BuildContext context, String phoneNumber) async {
  await askPermissions(Permission.microphone, (status) async {
      // status is always permanentlyDenied
      // even just after user installs the application
  });
}
```

### Configuration

**Version:** 1.x

`permission_handler: ^7.1.0`

**Platform:** 
- [ yes] :iphone: iOS

**Comment by abhinavsingh** [comment]
Looks like adding `'PERMISSION_MICROPHONE=1',` in Podfile fixed this issue.  Please feel free to close this bug, though plugin should still not return `permanentlyDenied` on iOS as documented.

**Comment by nouveau-riche** [comment]
I have added 'PERMISSION_MICROPHONE=1', but then also issue is coming and permission pop not opening.

This is my info.plist file with added microphone permission
<img width="1440" alt="info" src="https://user-images.githubusercontent.com/57298335/120594575-c7069780-c45e-11eb-8c05-e96399da9c30.png">

This is my podfile
<img width="1440" alt="Screenshot 1943-03-13 at 11 26 19" src="https://user-images.githubusercontent.com/57298335/120594623-db4a9480-c45e-11eb-9853-d9d019ef7b68.png">

**Comment by mvanbeusekom** [comment]
@abhinavsingh  this is on purpose since it makes the platform independent flow easier to understand:

- `PermissionStatus.denied` means permissions are unknown or denied but you can try again;
- `PermissionStatus.permanentlyDenied` means permissions have been denied and the user should grant permissions through the OS "Settings" (permissions dialogs will not be shown when requesting permission).

Otherwise you get in the situation where on Android `PermissionStatus.denied` means "permission status unknown or denied but you are allowed to request them" while on iOS the `PermissionStatus.denied` would mean "permission status denied, send the user to the Settings screen".

I agree that the documentation should be updated to reflect this correctly and is something I will work on. I will keep this issue open to track the progress on this.

**Comment by mvanbeusekom** [comment]
I just released version 8.0.1 which contains updates on the API documentation explaining the `PermissionStatus.permanentlyDenied` is used on all platforms to indicate permissions can no longer be requested and should be acquired through the general settings.

Thanks for raising this issue and making me aware of the wrong documentation.

**Comment by fisherjoe** [comment]
@mvanbeusekom The issue is still exist on iOS14.2 ! My permisstion_handler version is 8.1.2 .

**Comment by mvanbeusekom** [comment]
@fisherjoe have you recently updated from version 7 or lower to version 8? Have you made sure you enabled the microphone permission in your Podfile (have a look [here](https://github.com/Baseflow/flutter-permission-handler/issues/618) for more details)?

**Comment by Garciconx** [comment]
Same isue here but with the camera

**Comment by mvanbeusekom** [comment]
@Garciconx, the permissions work correctly in the example app associated with the plugin.

Please verify if you have configured the permission macros correctly in your `ios/Podfile` as documented in the README.md file under the iOS section.

If that doesn't work please include the contents of your `ios/Podfile`, `ios/Runner/Info.plist` and your `pubspec.yaml` files.

**Comment by Garciconx** [comment]
> @Garciconx, the permissions work correctly in the example app associated with the plugin.
> 
> Please verify if you have configured the permission macros correctly in your `ios/Podfile` as documented in the README.md file under the iOS section.
> 
> If that doesn't work please include the contents of your `ios/Podfile`, `ios/Runner/Info.plist` and your `pubspec.yaml` files.

Thank you very much, was de Podfile 👍 👍

**Comment by singh-karan-7** [comment]
The issue still exists. One should not have to edit the Podfile to make it work. Flutter is way too buggy for simple things.
