### ISSUE TITLE
Permission handler will crash when changing permissions in Location Settings 

### ISSUE THREAD

**Issue by florissmit1** [Baseflow/flutter-permission-handler#667]
## 🐛 Bug Report

Android:  The permission handler will crash when setting the Location Permission from `Ask every time` or `While in use` to `Allow all the time` and toggling the `Use precise location` from on to off. This issue will only occur when running your application in development mode. For testing I used the Android Emulator (API level 31) on my Macbook M1 and the Pixel 4A running on Android 12 Beta5.

### Expected behavior
The application shouldn't crash when changing the permissions in the Location Settings screen.
### Reproduction steps
1. Start the `permission_handler` example application.
2. Ask for location permission and choose `while in use` or `ask every time` in combination with `Precise location`.
3. Manually open the `permission_handler` Location Settings in Android.
4. Change `while in use` or `ask every time` to `Allow all the time` .
5. Toggle the `Precise location` switch to off.
6. Return to the application, the application should be stuck in the splash screen animation.
### Configuration
- Your `build.gradle` compileSdkVersion should be set to `31`.
- Run the example app in development mode.
- Add the COARSE, FINE and BACKGROUND permissions to your `AndroidManifest.xml`
**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by JDDV** [comment]
Using version `8.1.6`  (PR #666) of the `permission_handler` and using the newest Flutter SDK should fix this issue. This issue will be closed, if there are any questions about this please let us know!

**Comment by sonelektrikci** [comment]
I'm still getting the same problem. I'm using:
- permission_handler: ^8.3.0

When I manually don't allow the location permission, the app I created crashes.

**Comment by HonestKevin** [comment]
I have this issues.
