### ISSUE TITLE
Location Permission "always" returns "permanentlyDenied" when not requested yet

### ISSUE THREAD

**Issue by jocelyngriselle** [Baseflow/flutter-permission-handler#780]
## 🐛 Bug Report

After requesting Location Permission "While in use" and tapping "While in Use" in the native popup, the result of permissions is :
`Permission.locationWhenInUse.status => PermissionStatus.granted`
`Permission.locationAlways.status => PermissionStatus.permanentlyDenied`

### Expected behavior
After requesting Location Permission "While in use" and tapping "While in Use", the result of permissions should be :
`Permission.locationWhenInUse.Status => PermissionStatus.granted`
`Permission.locationWhenInUse.Status => PermissionStatus.denied`

### Reproduction steps
On ios :
1/ make a call to `Permission.locationWhenInUse.request()`
2/ tap "While in use in the native popup"
3/ test permissions with `Permission.locationAlways.status` and `Permission.locationWhenInUse.status`

### Configuration

**Version:** 8.3.0

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by kamami** [comment]
Same problem

**Comment by sgandro** [comment]
same problem. My app isn't in settings

**Comment by kamami** [comment]
Really nothing? Is this package even still under maintenance? This is a serious issue

**Comment by MaxEgg** [comment]
Same issue with permission.camera.  On IOS 15.3.1 with latest version 9.2.0; When disabling the permission in settings first the app crashes. And when turning it back on (the app crashes again) it will still returns permanentlyDenied.

**Comment by JulianGerman** [comment]
same issue in calendar permissions

**Comment by grumpycatz473** [comment]
also experiencing this issue for calendar permissions in ios

**Comment by mvanbeusekom** [comment]
Thanks to @lukaskurz for creating PR #800, this issue should have been resolved. Please run `flutter pub upgrade` to update to the latest version.

**Comment by jocelyngriselle** [comment]
Thanks for the PR but it doesn't fix the problem. 

Requesting `Permission.locationWhenInUse.request()` and clicking on "While in Use" still set `Permission.locationAlways.status` to `PermissionStatus.permanentlyDenied` where it should be `PermissionStatus.denied` since `Permission.always` hasn't been requested yet.

I have a minimal sample demo but it just display a button to request permission and display the status i'm not sure if this would help ?

**Comment by lukaskurz** [comment]
@jocelyngriselle Yep, seems you're right, your issue is not fixed by my PR, my bad.

It seems your issue stems from here

[LocationPermissionStrategy:131](https://github.com/Baseflow/flutter-permission-handler/blob/41c9af649aa749f44abb67d67e17a913c99a254d/permission_handler_apple/ios/Classes/strategies/LocationPermissionStrategy.m#L131)
```objc
if (permission == PermissionGroupLocationAlways) {
    switch (authorizationStatus) {
        case kCLAuthorizationStatusNotDetermined:
            return PermissionStatusDenied;
        case kCLAuthorizationStatusRestricted:
            return PermissionStatusRestricted;
        case kCLAuthorizationStatusAuthorizedWhenInUse:
        case kCLAuthorizationStatusDenied:
            return PermissionStatusPermanentlyDenied;
        case kCLAuthorizationStatusAuthorizedAlways:
            return PermissionStatusGranted;
    }
}
```

The issue with this is, that if you have only requested `whenInUse`, then your authorization is `whenInUse`. So the check for `always` should only be `denied`. However, if you ask to upgrade to `always` authorization and you are denied, then your authorization is still at `whenInUse`, but you are no longer allowed to ask for that permission (per iOS API, only 1 locationAlways request is allowed, and after that no more).

So you see, `whenInUse` authorization can mean both `permanentlyDenied` or `denied`.

I don't think there is a neat way to solve this in the code, I think we just have to document this behaviour (if it isn't already), so the developer can work around it accordingly. If it helps you (and any other people in this issue), this is similar to how I handle/solved this:

```dart
/// Checks if the user has given the app permission to use location services.
/// If not, the user is asked to grant the needed permission, locationAlways.
/// First, the locationWhenInUse is requested, then the locationAlways.
/// If `withoutRequest` is set to true, the permission is not requested, but only checked.
Future<PermissionStatus> _checkPermission({bool withoutRequest = false}) async {
  var alwaysPermission = await Permission.locationAlways.status;

  // We first need to request locationWhenInUse, because it is required to request locationAlways
  if(alwaysPermission.isGranted == false){
    var whenInUsePermission = await Permission.locationWhenInUse.status;
    if(whenInUsePermission.isGranted == false && !withoutRequest){
      whenInUsePermission = await Permission.locationWhenInUse.request();
      if(whenInUsePermission.isGranted == false){
        logger.d('locationWhenInUse denied by user');
        return whenInUsePermission;
      } else {
        logger.d('locationWhenInUse granted by user');
      }
    }
  }

  if(alwaysPermission.isGranted == false && !withoutRequest) {
    alwaysPermission = await Permission.locationAlways.request();

    if (alwaysPermission.isGranted == false) {
      logger.d('locationAlways permanently denied by user');
      return alwaysPermission;
    } else {
      logger.d('locationAlways granted by user');
    }
  }

  return alwaysPermission;
}
```

**Comment by danielocampo2** [comment]
shouldn't this be re-opened? I am experiencing the same issue and it seems like quite a relevant usecase to cover.

@lukaskurz @mvanbeusekom

**Comment by arjunvassarlabs** [comment]
If the Location services (for iOS) are turned off in the settings, the app will always show permanentlyDenied for 'location' permission. Also, even if I redirect the user to the settings using openAppSettings(), I cannot see the location permission toggle.

After turning on the Location services from the device settings, it shows 'denied', and at least I get the dialog when I request for the permission.

**Comment by 540765** [comment]
上面問題可能是你在應用兩個地方同時發起了權限獲取申請導致的問題，我也遇到過。如果確定你沒有犯錯，那麼插件在處理時無法進行等待或者直接返回拒絕

**Comment by Abdelazeem777** [comment]
Any updates?

**Comment by mohadel92** [comment]
@Abdelazeem777  Same issue 
on a freshly installed app (new simulator) the permission always return PermissionStatus.permanentlyDenied

**Comment by Abdelazeem777** [comment]
I found out that I missed a point on installations steps on iOS

https://github.com/Baseflow/flutter-permission-handler/tree/main/permission_handler

please check the first step on iOS section

the pod file modifications

**Comment by mohadel92** [comment]
> I found out that I missed a point on installations steps on iOS
> 
> https://github.com/Baseflow/flutter-permission-handler/tree/main/permission_handler
> 
> please check the first step on iOS section
> 
> the pod file modifications

@Abdelazeem777 
i was going to send a same reply
i found this mod to my pod file

1 - at the end of each pod file i add this line to force pod install to provide me with pods with min version >= 13
so that building doesn't fail
2- i have add some lines to require permission access

`post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
      '$(inherited)',

      'PERMISSION_CAMERA=1',
      'PERMISSION_PHOTOS=1',
      'PERMISSION_LOCATION=1',
      'PERMISSION_NOTIFICATIONS=1']
    
    end
  end
end`

**Comment by LouisRaverdy** [comment]
The issue is still persist, the pod file is well configured with the `'PERMISSION_LOCATION=1'` flag, the `whenInUse` is allowed, but if we check for the first time the status of the `always`, it still returns `permanentlyDenied`.
This is mostly important for our app to check that, cause we need to prompt a popup to explain why we need the always status.

**Comment by WojciechTrzasko** [comment]
Hi,
I have similar situation like @LouisRaverdy, where we want to explain why we need the always status and I'm also hitting the wall because of above issue.

@LouisRaverdy were you able to workaround it? I'm getting out of ideas :/
