### ISSUE TITLE
locationAlways in android 12

### ISSUE THREAD

**Issue by DJafari** [Baseflow/flutter-permission-handler#781]
calling `Permission.locationAlways.request()` doesn't show anything in android 12

**Comment by kamami** [comment]
Sme problem

**Comment by mono424** [comment]
+1 recently

**Comment by kamami** [comment]
Really nothing? Is this package even still under maintenance? This is a serious issue

**Comment by DJafari** [comment]
seems fixed in `9.0.1`

**Comment by KirillBorodin** [comment]
**9.0.2:** 
API 31 (Android 12) - The issue is still present;
API 30 (Android 11) - Fixed;

**Comment by yuriboeira11tx** [comment]
Same problem!

**Comment by neoacevedo** [comment]
The same issue I have but in Android 11.

**Comment by geisterfurz007** [comment]
Scrolling through changelogs I found an entry mentioning a section in the readme detailing that to request locationAlways, you have to request locationWhenInUse first. When doing that on Android 12, things "work". After the initial popup of the location permission for while the app is in use, the app's location settings are opened.

**Comment by Kampfotter** [comment]
We really need a fix for the location. When we ask for precise location we only get approximated but our app needs the precise location

**Comment by neoacevedo** [comment]
@Kampfotter did you used the accuracy:  Location.navigation option in changeSettings?

**Comment by JeroenWeener** [comment]
Hi everyone, thank you for reporting this issue.

I have investigated the issue, and there are some intricacies with Android starting from Android 10: https://developer.android.com/training/location/permissions#request-only-foreground.

It boils down to this: before you can request `Permission.locationAlways`, you need to obtain a foreground location permission via either `Permission.location` or `Permission.locationWhenInUse`. This has been described in the plugin in `permissions.dart`:

```dart
  /// Permission for accessing the device's location when the app is running in
  /// the background.
  ///
  /// Depending on the platform and version, the requirements are slightly
  /// different:
  ///
  /// **Android:**
  /// - When running on Android Q and above: Background Location Permission
  /// - When running on Android < Q: Fine and Coarse Location
  ///
  /// **iOS:** CoreLocation - Always
  /// - When requesting this permission, the user needs to grant permission for
  /// the `locationWhenInUse` permission first, clicking on the
  /// `Allow While Using App` option on the popup. After allowing the
  /// permission, the user can request the `locationAlways` permission and can
  /// click on the `Change To Always Allow` option.
  static const locationAlways = PermissionWithService._(4);
```

I think the documentation could use some work, because it is quite hard to find. Therefore, I have opened PRs #1133 and #1134. These should update both the documentation and add a section to the FAQ over on pub.dev.
